#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
if [ "$#" -ne 1 ]
  then echo "error: no network inferface specified"
  echo "specify the network interface like so:"
  echo "\"unspoof wlan0\""
  exit
fi

systemctl stop NetworkManager
macchanger -p $1
systemctl start NetworkManager
